# coding: utf-8

"""
    OSCR API

    OSCR API

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from OSCR_django_client.api.ladder_entries_api import LadderEntriesApi


class TestLadderEntriesApi(unittest.TestCase):
    """LadderEntriesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = LadderEntriesApi()

    def tearDown(self) -> None:
        pass

    def test_ladder_entries_list(self) -> None:
        """Test case for ladder_entries_list

        """
        pass

    def test_ladder_entries_read(self) -> None:
        """Test case for ladder_entries_read

        """
        pass


if __name__ == '__main__':
    unittest.main()
