# coding: utf-8

"""
    OSCR API

    OSCR API

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from OSCR_django_client.api.ladder_api import LadderApi


class TestLadderApi(unittest.TestCase):
    """LadderApi unit test stubs"""

    def setUp(self) -> None:
        self.api = LadderApi()

    def tearDown(self) -> None:
        pass

    def test_ladder_list(self) -> None:
        """Test case for ladder_list

        """
        pass

    def test_ladder_read(self) -> None:
        """Test case for ladder_read

        """
        pass


if __name__ == '__main__':
    unittest.main()
