# coding: utf-8

"""
    OSCR API

    OSCR API

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from OSCR_django_client.models.combat_log_upload_response import CombatLogUploadResponse

class TestCombatLogUploadResponse(unittest.TestCase):
    """CombatLogUploadResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CombatLogUploadResponse:
        """Test CombatLogUploadResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CombatLogUploadResponse`
        """
        model = CombatLogUploadResponse()
        if include_optional:
            return CombatLogUploadResponse(
                name = '0',
                updated = True,
                detail = '0',
                value = 1.337
            )
        else:
            return CombatLogUploadResponse(
                name = '0',
                updated = True,
                detail = '0',
                value = 1.337,
        )
        """

    def testCombatLogUploadResponse(self):
        """Test CombatLogUploadResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
