# Generated by Django 5.1.7 on 2025-03-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='update',
            name='url',
        ),
        migrations.AddField(
            model_name='update',
            name='url_appimage',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='update',
            name='url_msi',
            field=models.TextField(blank=True),
        ),
    ]
