# Generated by Django 4.2.9 on 2024-02-10 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Metadata",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("map", models.TextField()),
                ("difficulty", models.TextField()),
                ("summary", models.JSONField()),
                ("dps_chart", models.JSONField()),
                ("damage_chart", models.JSONField()),
                ("npc_dps_chart", models.JSONField()),
                ("npc_damage_chart", models.JSONField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CombatLog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("file", models.FileField(upload_to="uploads")),
                (
                    "metadata",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="combatlog.metadata",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
