# Generated by Django 4.2.9 on 2024-04-13 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("combatlog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metadata",
            name="difficulty",
            field=models.TextField(default=None, null=True),
        ),
    ]
