# Generated by Django 4.2.9 on 2024-05-12 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("combatlog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="combatlog",
            name="youtube",
            field=models.TextField(default=None, null=True),
        ),
    ]
