# Generated by Django 5.1.7 on 2025-04-29 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combatlog', '0003_metadata_damage_in_metadata_damage_out_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('prohibited', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
