# Generated by Django 4.2.9 on 2024-02-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("combatlog", "0003_remove_combatlog_file_combatlog_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="metadata",
            name="date_time",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
