# Generated by Django 4.2.9 on 2024-02-24 03:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("combatlog", "0004_metadata_date_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="combatlog",
            name="data",
        ),
    ]
