# Generated by Django 4.2.9 on 2024-02-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("combatlog", "0005_remove_combatlog_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="combatlog",
            name="name",
            field=models.TextField(default=None, null=True),
        ),
    ]
