# Generated by Django 4.2.9 on 2024-05-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ladder", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ladder",
            name="manual_review_threshold",
            field=models.IntegerField(default=0),
        ),
    ]
