# Generated by Django 4.2.9 on 2024-04-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ladder", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ladder",
            name="difficulty",
            field=models.TextField(blank=True, default=None),
        ),
    ]
