# Generated by Django 4.2.9 on 2024-05-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ladder", "0002_ladder_manual_review_threshold"),
    ]

    operations = [
        migrations.AddField(
            model_name="ladderentry",
            name="visible",
            field=models.BooleanField(default=True),
        ),
    ]
