# Generated by Django 4.2.9 on 2024-03-31 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ladder", "0002_ladder_is_solo"),
    ]

    operations = [
        migrations.AddField(
            model_name="ladder",
            name="is_space",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="Variant",
            fields=[
                ("name", models.TextField(primary_key=True, serialize=False)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("exclude_ground", models.ManyToManyField(to="ladder.variant")),
                ("exclude_space", models.ManyToManyField(to="ladder.variant")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="ladder",
            name="variant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ladder.variant",
            ),
        ),
    ]
