# Generated by Django 4.2.9 on 2024-04-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ladder", "0002_alter_ladder_difficulty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ladder",
            name="internal_difficulty",
            field=models.TextField(blank=True, default=None),
        ),
    ]
