# Generated by Django 4.2.9 on 2025-01-02 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ladder", "0003_ladderentry_visible"),
    ]

    operations = [
        migrations.AddField(
            model_name="variant",
            name="combat_time_source",
            field=models.TextField(default="combat_time"),
        ),
        migrations.AddField(
            model_name="variant",
            name="combat_time_threshold",
            field=models.FloatField(default=0.9),
        ),
    ]
