# Generated by Django 4.2.9 on 2024-03-31 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ladder", "0003_ladder_is_space_variant_ladder_variant"),
    ]

    operations = [
        migrations.AddField(
            model_name="variant",
            name="is_ground_variant",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="variant",
            name="is_space_variant",
            field=models.BooleanField(default=True),
        ),
    ]
