# Generated by Django 4.2.9 on 2024-04-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ladder", "0003_alter_ladder_internal_difficulty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ladder",
            name="difficulty",
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="ladder",
            name="internal_difficulty",
            field=models.TextField(default=None, null=True),
        ),
    ]
