# Generated by Django 4.2.9 on 2025-01-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ladder", "0004_variant_combat_time_source_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockedHandle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "handle",
                    models.TextField(
                        help_text="Player's @handle. You need to include the '@'"
                    ),
                ),
            ],
        ),
    ]
