# Generated by Django 5.1.7 on 2025-03-29 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0005_blockedhandle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variant',
            options={'get_latest_by': ['pk']},
        ),
    ]
