# Generated by Django 5.1.7 on 2025-03-29 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0006_alter_variant_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variant',
            options={'get_latest_by': 'pk'},
        ),
    ]
