# Generated by Django 4.2.9 on 2024-02-10 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("combatlog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ladder",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("difficulty", models.TextField()),
                ("metric", models.TextField()),
                ("internal_name", models.TextField()),
                ("internal_difficulty", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LadderEntry",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("player", models.TextField()),
                ("data", models.JSONField()),
                (
                    "combatlog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="combatlog.combatlog",
                    ),
                ),
                (
                    "ladder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ladder.ladder"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
